//
// Created by Anna on 05.05.18.
//

#ifndef COMMUTATOR_SERVERCOMMANDCONSTANTS_H
#define COMMUTATOR_SERVERCOMMANDCONSTANTS_H

#define QUERY_SERVER_VERSION "QUERY_VERSION"

#endif //COMMUTATOR_SERVERCOMMANDCONSTANTS_H
